server:
  port: 8080
spring:
  datasource:
    username: minran
    password: P@ssW0rd
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://125.124.6.53:3306/qr_code?characterEncoding=utf-8&useSSL=false
  redis:
    host: 125.124.6.53
    port: 6379
    password: 'P@ssW0rd'
    database: 0
#qiniu:
#  accessKey: nccHwQX42Io_TrucTSQmksJZhCm2hxtT_X-msF7N
#  secretKey: Pw3ziu4SFEoUDr640pl5-XYTj7r9rA6mhzv8coXN
#  bucket: myqrcode
